// Code generated by Prismic. DO NOT EDIT.

import Callout from "./Callout";
import CtaBanner from "./CtaBanner";
import Faq from "./Faq";
import FeatureGrid from "./FeatureGrid";
import Hero from "./Hero";
import ImageText from "./ImageText";
import LogoWall from "./LogoWall";
import MediaCards from "./MediaCards";
import RichText from "./RichText";
import Stats from "./Stats";
import Testimonial from "./Testimonial";

export const components = {
	callout: Callout,
	cta_banner: CtaBanner,
	faq: Faq,
	feature_grid: FeatureGrid,
	hero: Hero,
	image_text: ImageText,
	logo_wall: LogoWall,
	media_cards: MediaCards,
	rich_text: RichText,
	stats: Stats,
	testimonial: Testimonial
};